### ISSUE TITLE
Numba typing errors when querying index -cosine

### ISSUE THREAD

**Issue by dcurl47** [lmcinnes/pynndescent#120]
Hey, umap and pynndescent are super cool, but, I'm having major headaches on querying for neighbors in pynndescent. I've been experimenting with different versions of pynndescent and numba but none help. The issue pasted below has the following library versions:

numba: 0.51.2
pynndescent: 0.5.0

I also had the latests:
numba: 0.53.1
pynndescent: 0.5.3

with the same error

When I try to run, for example (I will make another ticket for euclidean distance since the error is a little different):
 
**index = NNDescent(np.array(some_file.fillna(-99)),metric='cosine')
index.query(pivoted.iloc[0],k=5)**

I get:
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-23-cd74454d0019> in <module>
      1 index = NNDescent(np.array(pivoted.fillna(-99)),metric='cosine')
----> 2 index.query(pivoted.iloc[0],k=5)

~/miniconda3/envs/pynn/lib/python3.7/site-packages/pynndescent/pynndescent_.py in query(self, query_data, k, epsilon)
   1597                 epsilon,
   1598                 self._visited,
-> 1599                 self.search_rng_state,
   1600             )
   1601         else:

~/miniconda3/envs/pynn/lib/python3.7/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~/miniconda3/envs/pynn/lib/python3.7/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~/miniconda3/envs/pynn/lib/python3.7/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'sum' of type float32

File "../../../../../miniconda3/envs/pynn/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1216:
        def search_closure(
            <source elided>
                if dist == alternative_dot or dist == alternative_cosine:
                    norm = np.sqrt((query_points[i] ** 2).sum())
                    ^

During: typing of get attribute at ~/miniconda3/envs/pynn/lib/python3.7/site-packages/pynndescent/pynndescent_.py (1216)

File "../../../../../miniconda3/envs/pynn/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1216:
        def search_closure(
            <source elided>
                if dist == alternative_dot or dist == alternative_cosine:
                    norm = np.sqrt((query_points[i] ** 2).sum())
                    ^

+++++++++++++++++++++++++++++++++++++++++++

**Comment by dcurl47** [comment]
Ok, figured it out. The problem was actually that I was passing a single entry from the table. If I pass 2 or more, everythings works like a charm.
