### ISSUE TITLE
Incompatibility with numpy 1.17

### ISSUE THREAD

**Issue by pavlin-policar** [lmcinnes/pynndescent#70]
I've pulled down the latest master (but the issue is already present in the latest release on both PyPI and conda-forge), using the latest version of numpy 1.17.0, and get the following error on import:

```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynndescent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pavlin/dev/pynndescent/pynndescent/__init__.py", line 3, in <module>
    from .pynndescent_ import NNDescent, PyNNDescentTransformer
  File "/home/pavlin/dev/pynndescent/pynndescent/pynndescent_.py", line 17, in <module>
    import pynndescent.threaded as threaded
  File "/home/pavlin/dev/pynndescent/pynndescent/threaded.py", line 60, in <module>
    @numba.njit("i8[:](f4[:, :], i8, i8, i8)", nogil=True)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/decorators.py", line 186, in wrapper
    disp.compile(sig)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 501, in stage_nopython_frontend
    self.locals)
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/compiler.py", line 1105, in type_inference_stage
    infer.propagate()
  File "/home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typeinfer.py", line 915, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function searchsorted at 0x7fbd99cb17b8>) with argument(s) of type(s): (array(float32, 1d, A), array(int64, 1d, C), side=Literal[str](left))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function _searchsorted.<locals>.searchsorted_inner at 0x7fbd92639950>) with argument(s) of type(s): (array(float32, 1d, A), int64)
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<ufunc 'isnan'>) with argument(s) of type(s): (int64)
 * parameterized
In definition 0:
    TypingError: ufunc 'isnan' using the loop 'l->?' not supported in this mode
    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typing/npydecl.py:114
In definition 1:
    TypingError: ufunc 'isnan' using the loop 'l->?' not supported in this mode
    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typing/npydecl.py:114
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<ufunc 'isnan'>)
[2] During: typing of call at /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py (2996)


File "../../miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2996:
    def searchsorted_inner(a, v):
        <source elided>
        n = len(a)
        if np.isnan(v):
        ^

    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typeinfer.py:915
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<ufunc 'isnan'>) with argument(s) of type(s): (int64)
 * parameterized
In definition 0:
    TypingError: ufunc 'isnan' using the loop 'l->?' not supported in this mode
    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typing/npydecl.py:114
In definition 1:
    TypingError: ufunc 'isnan' using the loop 'l->?' not supported in this mode
    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typing/npydecl.py:114
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<ufunc 'isnan'>)
[2] During: typing of call at /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py (2996)


File "../../miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py", line 2996:
    def searchsorted_inner(a, v):
        <source elided>
        n = len(a)
        if np.isnan(v):
        ^

    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typeinfer.py:915
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function _searchsorted.<locals>.searchsorted_inner at 0x7fbd92639950>)
[2] During: typing of call at /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py (3036)


File "../../miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py", line 3036:
        def searchsorted_impl(a, v, side='left'):
            <source elided>
            for view, outview in np.nditer((v, out)):
                index = loop_impl(a, view.item())
                ^

    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/typeinfer.py:915
In definition 1:
    ValueError: Invalid value given for 'side': unicode_type
    raised from /home/pavlin/miniconda3/envs/tmp/lib/python3.7/site-packages/numba/targets/arraymath.py:3029
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function searchsorted at 0x7fbd99cb17b8>)
[2] During: typing of call at /home/pavlin/dev/pynndescent/pynndescent/threaded.py (67)


File "pynndescent/threaded.py", line 67:
def chunk_heap_updates(heap_updates, num_heap_updates, n_vertices, chunk_size):
    <source elided>
    offsets = np.searchsorted(
        heap_updates[:num_heap_updates, 0], chunk_boundaries, side="left"
```

**Comment by lmcinnes** [comment]
That doesn't look good. I'm not sure exactly what would have changed to cause something like this -- it is definitely numba related. I'm on vacation right now, but I'll try to look at this when I get back.

**Comment by tomwhite** [comment]
I wasn't able to reproduce this with the following:

```
python3 -m venv venv
. venv/bin/activate
pip install pynndescent
python -c 'import pynndescent' # succeeds
```

This is with Python 3.7.2 on Mac. The package versions are:

```
Package      Version
------------ -------
joblib       0.13.2 
llvmlite     0.29.0 
numba        0.45.1 
numpy        1.17.0 
pip          18.1   
pynndescent  0.3.0  
scikit-learn 0.21.3 
scipy        1.3.1  
setuptools   40.6.2 
```

**Comment by pavlin-policar** [comment]
Sorry, I forgot to include the environment in the initial issue. I'm getting this consistently in a conda environment with

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0  
joblib                    0.13.2                   pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.29.0                   pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
numba                     0.44.1                   pypi_0    pypi
numpy                     1.17.0                   pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1  
opentsne                  0.3.8                    pypi_0    pypi
pip                       19.1.1                   py37_0  
pynndescent               0.3.1                     dev_0    <develop>
python                    3.7.3                h0371630_0  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.21.2                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
sqlite                    3.28.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
```

Channel `pypi` indicates that it was installed by running `pip install <package>`, the others were installed using conda. I'm running Arch Linux x86_64 with kernel 5.1.15-arch1-1-ARCH.

**Comment by pavlin-policar** [comment]
I noticed my environment had some openTSNE things in it, so I set up a new minimal environment like this

```
conda create --name tmp
conda activate tmp
conda install python=3.7.3
pip install pynndescent
python -c 'import pynndescent'           
```

which now results in a segfault

zsh: segmentation fault (core dumped)  python -c 'import pynndescent'

**Comment by pavlin-policar** [comment]
After a bit more hunting, I found the issue is not specific to `pynndescent`, but to numba in general, and it only occurs in a conda environment.

**Comment by slinnarsson** [comment]
In case it helps anyone, I had the same issue on a brand new install of Anaconda (version 2019.07 for macOS). Doing `conda update numba` gave me numba version 0.45.1, which resolved the issue.
